### ISSUE TITLE
Why plus 1 to forget gates

### ISSUE THREAD

**Issue by marcwww** [jihunchoi/unsupervised-treelstm#10]
1. Why there are additional [plus 1 operations](https://github.com/jihunchoi/unsupervised-treelstm/blob/master/model/treelstm.py#L41) for the forget gates?

2. When using leaf_rnn and bidirectional_lstm, why not directly use the original pytorch implementation (i.e. LSTM and the pack_padded_sequence function)?

Thanks a lot.

**Comment by jihunchoi** [comment]
Hi! Sorry for the late reply.
1. Please refer to my answer to the issue: https://github.com/jihunchoi/unsupervised-treelstm/issues/8.
2. The original PyTorch implementation does not return cell states, which are required to compute tree-LSTM states. So I implemented the custom LSTM using `LSTMCell` to collect cell states obtained from `LSTMCell` at each step.

Thanks!
