### ISSUE TITLE
how to extract the tree structure?

### ISSUE THREAD

**Issue by wangshaonan** [jihunchoi/unsupervised-treelstm#2]
Thanks for the code, it gets great results. However, to have a better understanding of the model, is there a script to extract the tree structure?

**Comment by jihunchoi** [comment]
Hi, currently there's no script for visualizing tree structures.
However I think it can be simply done by turning on the `return_select_masks` flag of `BinaryTreeLSTM` object.
Though I've drawn tree structures using hard-coded latex scripts, there's a nice implementation that helps draw the structure: https://github.com/mrdrozdov/latex-trees.

**Comment by jihunchoi** [comment]
It's too late, but I uploaded the example code for tree extraction: https://github.com/jihunchoi/unsupervised-treelstm/blob/master/extract_trees.ipynb
