### ISSUE TITLE
Is there any pretrained model?

### ISSUE THREAD

**Issue by easonnie** [jihunchoi/unsupervised-treelstm#5]
Hi,
Thanks for the repository.
I was wondering if there is any pretrained model that I could load directly to achieve the reported result on SNLI (86.0%).
If not, could you provide a detailed instruction on how to achieve the reported SNLI result? It seems that there is not recommended parameters for training.

Thanks in advance.

**Comment by jihunchoi** [comment]
Hi Yixin!
Sorry for the late reply, I was in a military training camp. :(
I uploaded some checkpoints in the latest commit. Hope they help!
(Files are somewhat huge, and I don't think it's a good idea to contain checkpoints in the repo, but anyway...)

**Comment by easonnie** [comment]
Much appreciated.

**Comment by easonnie** [comment]
Sorry to bother again. Could you also upload the vocabulary file? I still can't reproduce your result. I got around 38% using your pretrained parameter. I guess there is a mismatch between the vocabulary.

**Comment by jihunchoi** [comment]
Hi,
I just uploaded the vocabulary file.
You can load it using Vocab.from_file method.
You may also find some usages from dump_dataset.py script, and I hope it would help.
Please let me know if there’s any unclear point left.

Thanks!
