### ISSUE TITLE
Dataset for SNLI

### ISSUE THREAD

**Issue by nitishgupta** [jihunchoi/unsupervised-treelstm#7]
Hi, How do I train on SNLI. Seems like the code requires a pickled dataset class. Also the argument names in snli.train are mismatching.

**Comment by jihunchoi** [comment]
Hi, about the argument name mismatches, please see my answer to another issue (https://github.com/jihunchoi/unsupervised-treelstm/issues/6).

And you can generate dataset pickle files running `snli.build_vocab` then `snli.dump_dataset`.
Or you can skip the `snli.build_vocab` if you use the vocabulary file I uploaded on `pretrained/snli_vocab.txt`.
