### ISSUE TITLE
I'm so confused about tree-lstm layer equation

### ISSUE THREAD

**Issue by daqingliu** [jihunchoi/unsupervised-treelstm#8]
According to your paper's equation (2),
it should be: ``` c = cl*fl.sigmoid() + cr*fr.sigmoid() + u.tanh()*i.sigmoid() ```
but in your code, it's: https://github.com/jihunchoi/unsupervised-treelstm/blob/39d9823dcb9806d6af78ac4d3547305c66ab10b7/model/treelstm.py#L40

Why **+1** here? Looking forward your reply~

**Comment by jihunchoi** [comment]
Hi! That is a typically used technique for training LSTMs. (For details, see http://proceedings.mlr.press/v37/jozefowicz15.pdf)
The paper recommends initializing *biases* of a forget gate with positive values (1), but it is equivalent to initializing biases with zeroes and then adding 1 explicitly in the forward computation.
(tensorflow also adopts this technique; see line 863--868 in https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/python/ops/rnn_cell_impl.py)
