### ISSUE TITLE
about  train_dataset: SNLIDataset = pickle.load(f)

### ISSUE THREAD

**Issue by SongFGH** [jihunchoi/unsupervised-treelstm#9]
In this code: /snil/train.py
 with open(args.train_data, 'rb') as f:
        train_dataset: SNLIDataset = pickle.load(f)
I can't understand train_dataset: SNLIDataset = pickle.load(f)!
and when I also get a mistake:
ipdb> ValueError: invalid literal for int() with base 10: 'old_label\tsentence1_binary_parse\tsentence2_binary_parse\tsentence1_parse\tsentence2_parse\tsentence1\tsentence2\tcaptionID\tpairID\tlabel1\tlabel2\tlabel3\tlabel4\tlabel5\n
for the file f, I use /data/snli_1.0_train.txt.
So, can you help me?

**Comment by SongFGH** [comment]
for the file f:/data/snli_1.0_train.jsonl
I get a mistake:UnpicklingError: invalid load key, '{'.

**Comment by jihunchoi** [comment]
Hi, sorry for the extremely late check. I wasn't aware that this issue is posted...

The code uses "pickled" datasets, not JSON files due to the speed issue.
You can make pickled datasets via `dump_dataset` script.

Sorry for the late reply!
